# Titel

In [1]:
import pandas as pd

#to generate random numbers
from numpy.random import randn

In [3]:
#2dimensional data structures - list
print("Some two-dimensional data types:")
list_2dim = [[10112,"Berlin",3460725],[20095,"Hamburg",1786445],[80331,"München",1353185]]
print("\nThis is a simple 2dim list:")
print (list_2dim)
print(type(list_2dim))

print(list_2dim[1][2])

Some two-dimensional data types:

This is a simple 2dim list:
[[10112, 'Berlin', 3460725], [20095, 'Hamburg', 1786445], [80331, 'München', 1353185]]
<class 'list'>
1786445

In [4]:
#2dimensional data structures - array
array_ran = randn(3,3)
print("\nThis is a simple 2dim array:")
print (array_ran)
print(type(array_ran))

print (array_ran[0,1])

This is a simple 2dim array:
[[ 2.05424956  1.23790002  0.4634031 ]
 [-0.42714565  0.226242    0.54771967]
 [ 0.62912783 -0.53469206  1.26507186]]
<class 'numpy.ndarray'>
1.237900021706217

In [5]:
#2dimensional data structures - PANDAS data frame
df = pd.DataFrame(array_ran,index=['ID1','ID2','ID3'],columns=['A1','A2','A3'])
print(type(df))
print("\nThis is a PANDAS dataframe:")
df

<class 'pandas.core.frame.DataFrame'>

This is a PANDAS dataframe:

           A1        A2        A3
ID1  2.054250  1.237900  0.463403
ID2 -0.427146  0.226242  0.547720
ID3  0.629128 -0.534692  1.265072

In [6]:
#select column
df['A1']

ID1    2.054250
ID2   -0.427146
ID3    0.629128
Name: A1, dtype: float64

In [7]:
#select list of columns 
df[['A1','A3']]

           A1        A3
ID1  2.054250  0.463403
ID2 -0.427146  0.547720
ID3  0.629128  1.265072

In [9]:
#create new column
df['A1+A2']=df['A1']+df['A2']
df

           A1        A2        A3     A1+A2
ID1  2.054250  1.237900  0.463403  3.292150
ID2 -0.427146  0.226242  0.547720 -0.200904
ID3  0.629128 -0.534692  1.265072  0.094436

In [10]:
#drop column temporarily
df.drop('A1+A2',axis=1)

           A1        A2        A3
ID1  2.054250  1.237900  0.463403
ID2 -0.427146  0.226242  0.547720
ID3  0.629128 -0.534692  1.265072

In [11]:
df

           A1        A2        A3     A1+A2
ID1  2.054250  1.237900  0.463403  3.292150
ID2 -0.427146  0.226242  0.547720 -0.200904
ID3  0.629128 -0.534692  1.265072  0.094436

In [12]:
#drop column permanently
df.drop('A1+A2',axis=1,inplace=True)

In [11]:
df

           A1        A2        A3
ID1  0.189403 -0.558980 -0.158466
ID2  2.166957 -1.258731 -0.602858
ID3  1.403955  0.496960  0.770644

In [13]:
#select row
df.loc['ID1']

A1    2.054250
A2    1.237900
A3    0.463403
Name: ID1, dtype: float64

In [14]:
#drop row temp
df.drop('ID1',axis=0)

           A1        A2        A3
ID2 -0.427146  0.226242  0.547720
ID3  0.629128 -0.534692  1.265072

In [15]:
#select rows and columns at once
df.loc[['ID2','ID3'],['A1','A2']]

           A1        A2
ID2 -0.427146  0.226242
ID3  0.629128 -0.534692

In [16]:
df

           A1        A2        A3
ID1  2.054250  1.237900  0.463403
ID2 -0.427146  0.226242  0.547720
ID3  0.629128 -0.534692  1.265072

In [17]:
#conditional selection
df >= 0

        A1     A2    A3
ID1   True   True  True
ID2  False   True  True
ID3   True  False  True

In [19]:
#conditional selection
df[df['A3']>=1]
#df[df['A3']<0]['A1']

           A1        A2        A3
ID3  0.629128 -0.534692  1.265072

In [20]:
#descriptive statistics
df.describe()

             A1        A2        A3
count  3.000000  3.000000  3.000000
mean   0.752077  0.309817  0.758732
std    1.245258  0.889246  0.440525
min   -0.427146 -0.534692  0.463403
25%    0.100991 -0.154225  0.505561
50%    0.629128  0.226242  0.547720
75%    1.341689  0.732071  0.906396
max    2.054250  1.237900  1.265072

In [21]:
#non-missing values and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, ID1 to ID3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A1      3 non-null      float64
 1   A2      3 non-null      float64
 2   A3      3 non-null      float64
dtypes: float64(3)
memory usage: 204.0+ bytes

In [23]:
df

           A1        A2        A3
ID1  2.054250  1.237900  0.463403
ID2 -0.427146  0.226242  0.547720
ID3  0.629128 -0.534692  1.265072