Student-DB Extension: Extend the university data frame by adding single lines of code according to the comments below!

In [10]:
#PANDAS Data Frames
import pandas as pd

In [11]:
list_2dim = [[100112,"Jim Collins","WI7",4],[120095,"Martin Schrader","WI3",7],[180331,"Achim Zahn","WI7",1],[180332,"Mark Maier","OM3",1]]
#Start with the provided 2dim-list and create a data frame 
df = pd.DataFrame(list_2dim,index=['ID1','ID2','ID3','ID4'],columns=['ID','Name','FoS','Semesters'])

#Rename the column which stores the information about field of study
df=df.rename(columns = {'FoS':'Study_Program'})
#Rename all indices to ['ID-1', 'ID-2', 'ID-3', 'ID-4']
df.index=['ID-1', 'ID-2', 'ID-3', 'ID-4']
#Print only column names to check 
print(str(df.columns))
#Print only index names to check 
print(str(df.index))

Index(['ID', 'Name', 'Study_Program', 'Semesters'], dtype='object')
Index(['ID-1', 'ID-2', 'ID-3', 'ID-4'], dtype='object')

In [12]:
df

          ID             Name Study_Program  Semesters
ID-1  100112      Jim Collins           WI7          4
ID-2  120095  Martin Schrader           WI3          7
ID-3  180331       Achim Zahn           WI7          1
ID-4  180332       Mark Maier           OM3          1

In [ ]:
#Select all rows, but only last two columns without using column or index names
#One alternative
#df.iloc[:, 2:]

#Another one
#df.iloc[:, [2,3]]

#Another one
df.iloc[:, -2:]

     Study_Program  Semesters
ID-1           WI7          4
ID-2           WI3          7
ID-3           WI7          1
ID-4           OM3          1

In [16]:
#Select first and second attribute from first and second row, without using column or index names
#One alternative
#df.iloc[:2, :2]

#Another one
df.iloc[[0,1], [0,1]]

          ID             Name
ID-1  100112      Jim Collins
ID-2  120095  Martin Schrader

In [18]:
#Combine positional and label-based indexing to select Name and Semesters of the students in the last two rows
#One alternative
#df.iloc[-2:, df.columns.get_indexer(['Name', 'Semesters'])]

#Another one
df.iloc[df.index.get_indexer(['ID-3', 'ID-4']),[1,3]]

            Name  Semesters
ID-3  Achim Zahn          1
ID-4  Mark Maier          1