# Join and Append Data Frames

Student-DB Extension: Extend your university database data frame from the previous exercise

Start with the following data frame from the last exercise

In [5]:
#PANDAS Data Frames
import pandas as pd

print("The original data frame:")
list_2dim = [[100112,"Jim Collins","Wifo",4],[120095,"Martin Schrader","Wifo",7],[180331,"Achim Zahn","OMM",1]]
df = pd.DataFrame(list_2dim,index=['ID1','ID2','ID3'],columns=['ID','Name','FoS','Semesters'])
df

The original data frame:

         ID             Name   FoS  Semesters
ID1  100112      Jim Collins  Wifo          4
ID2  120095  Martin Schrader  Wifo          7
ID3  180331       Achim Zahn   OMM          1

Create a new data frame storing ID and age of the three students

Set index of df to the attribute 'ID': 

df=df.set_index('ID')

Similarily set index of new data frame to the attribute 'ID

Join new data frame with the first one and show results!

In [6]:
list_2dim = [[100112, 24],[120095,27],[180331,23]]
df2 = pd.DataFrame(list_2dim,index=['ID1','ID2','ID3'],columns=['ID','Age'])

df=df.set_index('ID')
df2=df2.set_index('ID')

print("The joined data frame:")
df=df.join(df2, lsuffix='_df', rsuffix='_df2')
df

The joined data frame:

                   Name   FoS  Semesters  Age
ID
100112      Jim Collins  Wifo          4   24
120095  Martin Schrader  Wifo          7   27
180331       Achim Zahn   OMM          1   23

Create a dictionary to store an additional student

Transform the dictionary to a series and name your series object. The name is the "ID" of the student in this case

Append the series object tp your joined data frame

In [7]:
dict_obj = {'Name': 'Klaus Mayer', 'FoS': 'Wifo', 'Semesters': 2, 'Age': 20}

series = pd.Series(dict_obj, name='180555')

#df=df.append(series)
series_df = series.to_frame().T
df = pd.concat([df, series_df])
df

                   Name   FoS Semesters Age
100112      Jim Collins  Wifo         4  24
120095  Martin Schrader  Wifo         7  27
180331       Achim Zahn   OMM         1  23
180555      Klaus Mayer  Wifo         2  20

Append data frame by dictionary

1. Transform dictionary to data frame "df_dict" using method from_dict
2. Add index to df_dict ("ID"-values of the students)
3. Append original data frame by df_dict

In [8]:
data = {'Name': ['John Doe', 'Henry Miller'], 'FoS': ['IW', 'OMM'],'Semesters': [3, 4], 'Age': [23, 24]}

#Transform dictionary to data frame "df_dict" using method from_dict
df_dict=pd.DataFrame.from_dict(data)

#Add index to df_dict ("ID"-values of the students)
df_dict.index=[100201,100202]

#Append orignial data frame by df_dict
#df=df.append(df_dict)
# Convert the dictionary to a DataFrame
dict_df = pd.DataFrame.from_dict(df_dict)


# Concatenate the DataFrame and the dictionary DataFrame vertically
df = pd.concat([df, dict_df])
df

                   Name   FoS Semesters Age
100112      Jim Collins  Wifo         4  24
120095  Martin Schrader  Wifo         7  27
180331       Achim Zahn   OMM         1  23
180555      Klaus Mayer  Wifo         2  20
100201         John Doe    IW         3  23
100202     Henry Miller   OMM         4  24