In [1]:
#PANDAS Data Frames
import pandas as pd

#to generate random numbers
from numpy.random import randn

In [2]:
#create data frame size 5*5 containing random numbers
df = pd.DataFrame(randn(5,5),index=['ID1','ID2','ID3','ID4','ID5'],columns=['A1','A2','A3','A4','A5'])
df

           A1        A2        A3        A4        A5
ID1 -1.840842  0.133535  0.499327 -0.179407  0.538427
ID2  0.422325 -2.574990  0.777746  0.642142 -0.560983
ID3 -0.375776  0.477382  2.364702 -0.528763 -2.690722
ID4  2.036815 -1.152119 -1.495764  1.287835 -0.172980
ID5  0.587797  0.021853 -0.616798  0.712899  0.246566

# Change column and index names

In [3]:
#print columns and index
print(str(df.columns))
print(str(df.index))

Index(['A1', 'A2', 'A3', 'A4', 'A5'], dtype='object')
Index(['ID1', 'ID2', 'ID3', 'ID4', 'ID5'], dtype='object')

In [4]:
#change columns
df.columns=['B1', 'B2', 'B3', 'B4', 'B5']
df

           B1        B2        B3        B4        B5
ID1 -1.840842  0.133535  0.499327 -0.179407  0.538427
ID2  0.422325 -2.574990  0.777746  0.642142 -0.560983
ID3 -0.375776  0.477382  2.364702 -0.528763 -2.690722
ID4  2.036815 -1.152119 -1.495764  1.287835 -0.172980
ID5  0.587797  0.021853 -0.616798  0.712899  0.246566

In [5]:
#change index
df.index=['First-ID', 'ID2', 'ID3', 'ID4', 'ID5']
#change columns
df.columns=['A1', 'A2', 'A3', 'A4', 'B5']
df

                A1        A2        A3        A4        B5
First-ID -1.840842  0.133535  0.499327 -0.179407  0.538427
ID2       0.422325 -2.574990  0.777746  0.642142 -0.560983
ID3      -0.375776  0.477382  2.364702 -0.528763 -2.690722
ID4       2.036815 -1.152119 -1.495764  1.287835 -0.172980
ID5       0.587797  0.021853 -0.616798  0.712899  0.246566

In [6]:
#Change just one column
df=df.rename(columns = {'B5':'A5'})

#Change just one index
df=df.rename(index = {'First-ID':'ID1'})
df

           A1        A2        A3        A4        A5
ID1 -1.840842  0.133535  0.499327 -0.179407  0.538427
ID2  0.422325 -2.574990  0.777746  0.642142 -0.560983
ID3 -0.375776  0.477382  2.364702 -0.528763 -2.690722
ID4  2.036815 -1.152119 -1.495764  1.287835 -0.172980
ID5  0.587797  0.021853 -0.616798  0.712899  0.246566

# Selection and Slicing

In [7]:
#Select values < 0
df_le1=df[df<0]
df_le1
#NaN=Not a Number

           A1        A2        A3        A4        A5
ID1 -1.840842       NaN       NaN -0.179407       NaN
ID2       NaN -2.574990       NaN       NaN -0.560983
ID3 -0.375776       NaN       NaN -0.528763 -2.690722
ID4       NaN -1.152119 -1.495764       NaN -0.172980
ID5       NaN       NaN -0.616798       NaN       NaN

In [8]:
#Drop NaN/missing values
df_le1.dropna()

Empty DataFrame
Columns: [A1, A2, A3, A4, A5]
Index: []

In [9]:
df

           A1        A2        A3        A4        A5
ID1 -1.840842  0.133535  0.499327 -0.179407  0.538427
ID2  0.422325 -2.574990  0.777746  0.642142 -0.560983
ID3 -0.375776  0.477382  2.364702 -0.528763 -2.690722
ID4  2.036815 -1.152119 -1.495764  1.287835 -0.172980
ID5  0.587797  0.021853 -0.616798  0.712899  0.246566

In [10]:
# slice all rows, some columns 
df.loc[:, ['A2', 'A4']]

           A2        A4
ID1  0.133535 -0.179407
ID2 -2.574990  0.642142
ID3  0.477382 -0.528763
ID4 -1.152119  1.287835
ID5  0.021853  0.712899

In [11]:
# slice all columns, some rows
df.loc[['ID2', 'ID4'],:]

           A1        A2        A3        A4        A5
ID2  0.422325 -2.574990  0.777746  0.642142 -0.560983
ID4  2.036815 -1.152119 -1.495764  1.287835 -0.172980

In [12]:
# slicing by index: iloc
#first column and row: index = 0
#last index in range can equal, but not exceed number of rows

df.iloc[0:3, 1:4]

           A2        A3        A4
ID1  0.133535  0.499327 -0.179407
ID2 -2.574990  0.777746  0.642142
ID3  0.477382  2.364702 -0.528763

In [13]:
#last single index in range needs to be smaller than number of rows
#this works
print(df.iloc[4, 0:4])

#this does not work
df.iloc[5, 0:4]

A1    0.587797
A2    0.021853
A3   -0.616798
A4    0.712899
Name: ID5, dtype: float64

IndexError: single positional indexer is out-of-bounds

In [14]:
# slice all columns, some rows
df.iloc[[2,4], :]

           A1        A2        A3        A4        A5
ID3 -0.375776  0.477382  2.364702 -0.528763 -2.690722
ID5  0.587797  0.021853 -0.616798  0.712899  0.246566

In [15]:
# slice all rows, some columns
df.iloc[:, 2:4]

           A3        A4
ID1  0.499327 -0.179407
ID2  0.777746  0.642142
ID3  2.364702 -0.528763
ID4 -1.495764  1.287835
ID5 -0.616798  0.712899

In [16]:
# slice with range closed to one side
df.iloc[:, :3]

           A1        A2        A3
ID1 -1.840842  0.133535  0.499327
ID2  0.422325 -2.574990  0.777746
ID3 -0.375776  0.477382  2.364702
ID4  2.036815 -1.152119 -1.495764
ID5  0.587797  0.021853 -0.616798

In [17]:
#Combining positional and label-based indexing
#Single attribute
df.iloc[0: 3, df.columns.get_loc('A2')]

ID1    0.133535
ID2   -2.574990
ID3    0.477382
Name: A2, dtype: float64

In [18]:
#Combining positional and label-based indexing
#Multiple attributes
df.iloc[[0, 2], df.columns.get_indexer(['A3', 'A5'])]

           A3        A5
ID1  0.499327  0.538427
ID3  2.364702 -2.690722